name: Test and release

on:
  push:
    branches: [develop]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  lint:
    name: golang lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: idp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: toor
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
